#ifndef SMTPEXPORTS_H
#define SMTPEXPORTS_H

/* SM
#ifdef SMTP_BUILD
#define SMTP_EXPORT Q_DECL_EXPORT
#else
#define SMTP_EXPORT Q_DECL_IMPORT
#endif
SM */
#define SMTP_EXPORT

#endif // SMTPEXPORTS_H
